/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario_2;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistroAlumnos extends javax.swing.JFrame {

    
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Alumno> listaAlumnos = new ArrayList<Alumno>();
    
    public RegistroAlumnos() {
        initComponents();
        setIconImage(getIconImage());
        this.setTitle("REGISTRO DE ALUMNOS");
        this.setLocationRelativeTo(null);
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CARRERA");
        modelo.addColumn("GRUPO");
        modelo.addColumn("SEMESTRE");
        modelo.addColumn("PROMEDIO");
        refrescarTabla();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Icono/icono.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombreAlumno = new javax.swing.JTextField();
        spnpromedioAlumno = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblregistroAlumos = new javax.swing.JTable();
        cbocarreraAlumno = new javax.swing.JComboBox<>();
        cbogrupoAlumno = new javax.swing.JComboBox<>();
        btnsemestreAlumno = new javax.swing.JComboBox<>();
        agregarAlumno = new javax.swing.JButton();
        eliminarAlumno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 110, 30));

        jLabel2.setText("Carrera");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 110, 30));

        jLabel3.setText("Grupo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 110, 30));

        jLabel4.setText("Semestre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 110, 30));

        jLabel5.setText("Promedio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 110, 30));
        getContentPane().add(txtnombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, 30));

        spnpromedioAlumno.setModel(new javax.swing.SpinnerNumberModel(10.0d, 5.0d, 10.0d, 0.1d));
        getContentPane().add(spnpromedioAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        tblregistroAlumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblregistroAlumos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 880, 250));

        cbocarreraAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISC", "IGE", "IND", "IIAS", "IQ" }));
        getContentPane().add(cbocarreraAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        cbogrupoAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "104", "301", "302", "303", "304", "501", "502", "503", "504" }));
        getContentPane().add(cbogrupoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        btnsemestreAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primer Semestre", "Tercer Semestre", "Quinto Semestre" }));
        getContentPane().add(btnsemestreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        agregarAlumno.setText("Agregar");
        agregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 130, 40));

        eliminarAlumno.setText("Eliminar");
        eliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAlumnoActionPerformed
        try {
            Alumno alumno = new Alumno();
            alumno.setNombre(txtnombreAlumno.getText());
            alumno.setCarrera(cbocarreraAlumno.getSelectedItem().toString());
            alumno.setGrupo(Integer.parseInt(cbogrupoAlumno.getSelectedItem().toString()));
            alumno.setSemestre(btnsemestreAlumno.getSelectedItem().toString());
            alumno.setPromedio(Double.parseDouble(spnpromedioAlumno.getValue().toString()));
            listaAlumnos.add(alumno);
            refrescarTabla();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"ERROR al agregar alumno");
        }
    }//GEN-LAST:event_agregarAlumnoActionPerformed

    private void eliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAlumnoActionPerformed
        txtnombreAlumno.setText("");
        cbocarreraAlumno.setSelectedIndex(0);
        cbocarreraAlumno.setSelectedIndex(0);
        btnsemestreAlumno.setSelectedIndex(0);
        spnpromedioAlumno.setValue(10);
    }//GEN-LAST:event_eliminarAlumnoActionPerformed
private void refrescarTabla(){
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);        
        }
        for (Alumno alumno : listaAlumnos) {
            Object tt[] = new Object[5];
            tt[0]=alumno.getNombre();
            tt[1]=alumno.getCarrera();
            tt[2]=alumno.getGrupo();
            tt[3]=alumno.getSemestre();
            tt[4]=alumno.getPromedio();
            modelo.addRow(tt);
        }
        tblregistroAlumos.setModel(modelo);
    }    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAlumno;
    private javax.swing.JComboBox<String> btnsemestreAlumno;
    private javax.swing.JComboBox<String> cbocarreraAlumno;
    private javax.swing.JComboBox<String> cbogrupoAlumno;
    private javax.swing.JButton eliminarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnpromedioAlumno;
    private javax.swing.JTable tblregistroAlumos;
    private javax.swing.JTextField txtnombreAlumno;
    // End of variables declaration//GEN-END:variables
}
